Num_Wins_L10G: {Description: 'Number of wins in the last 10 games, NaN if not applicable',
                Parameter_Name: Num_Wins_L10G,
                column_required: 'team_won',
                method_of_compute: count,
                rolling_window_required: 10}

Num_Wins_L9G: {Description: 'Number of wins in the last 9 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L9G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 9}

Num_Wins_L8G: {Description: 'Number of wins in the last 8 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L8G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 8}

Num_Wins_L7G: {Description: 'Number of wins in the last 7 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L7G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 7}

Num_Wins_L6G: {Description: 'Number of wins in the last 6 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L6G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 6}

Num_Wins_L5G: {Description: 'Number of wins in the last 5 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L5G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 5}

Num_Wins_L4G: {Description: 'Number of wins in the last 4 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L4G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 4}

Num_Wins_L3G: {Description: 'Number of wins in the last 3 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L3G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 3}

Num_Wins_L2G: {Description: 'Number of wins in the last 2 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L2G,
               column_required: 'team_won',
               method_of_compute: count,
               rolling_window_required: 2}

Win_LG: {Description: 'Indicator of winning the last game played',
         Parameter_Name: Win_LG,
         column_required: 'team_won',
         method_of_compute: count,
         rolling_window_required: 1}

Num_Losses_L10G: {Description: 'Number of losses in the last 10 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L10G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 10}

Num_Losses_L9G: {Description: 'Number of losses in the last 9 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L9G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 9}

Num_Losses_L8G: {Description: 'Number of losses in the last 8 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L8G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 8}

Num_Losses_L7G: {Description: 'Number of losses in the last 7 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L7G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 7}

Num_Losses_L6G: {Description: 'Number of losses in the last 6 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L6G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 6}

Num_Losses_L5G: {Description: 'Number of losses in the last 5 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L5G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 5}

Num_Losses_L4G: {Description: 'Number of losses in the last 4 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L4G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 4}

Num_Losses_L3G: {Description: 'Number of losses in the last 3 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L3G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 3}

Num_Losses_L2G: {Description: 'Number of losses in the last 2 games, NaN if not applicable',
                Parameter_Name: Num_Losses_L2G,
                column_required: 'team_lost',
                method_of_compute: count,
                rolling_window_required: 2}

Loss_LG: {Description: 'Indicator of losing the last game played, NaN if not applicable',
          Parameter_Name: Lose_LG,
          column_required: 'team_lost',
          method_of_compute: count,
          rolling_window_required: 1}
