NBA_Team_stats_raw:
  - 2009-2010_NBA_Box_Score_Team-Stats.xlsx
  - 2010-2011_NBA_Box_Score_Team-Stats.xlsx
  - 2011-2012_NBA_Box_Score_Team-Stats.xlsx
  - 2012-2013_NBA_Box_Score_Team-Stats.xlsx
  - 2013-2014_NBA_Box_Score_Team-Stats.xlsx
  - 2014-2015_NBA_Box_Score_Team-Stats.xlsx
  - 2015-2016_NBA_Box_Score_Team-Stats.xlsx
  - 2016-2017_NBA_Box_Score_Team-Stats.xlsx
  - 2017-2018_NBA_Box_Score_Team-Stats.xlsx
  - 2018-2019_NBA_Box_Score_Team-Stats.xlsx
NBA_Team_Stats_2010-2019_rolling_avg:
  - 2009-2010_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2010-2011_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2011-2012_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2012-2013_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2013-2014_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2014-2015_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2015-2016_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2016-2017_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2017-2018_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
  - 2018-2019_NBA_Box_Score_Team-Stats_w_rolling_avgs.csv
NBA_Team_Stats_2010-2019_rolling_avg_win_loss:
   - 2009-2010_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2010-2011_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2011-2012_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2012-2013_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2013-2014_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2014-2015_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2015-2016_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2016-2017_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
   - 2017-2018_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss.csv
NBA_Team_Stats_2010-2019_Rolling_Avg_Win_Loss_pts_diff:
   - 2009-2010_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2010-2011_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2011-2012_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2012-2013_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2013-2014_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2014-2015_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2015-2016_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2016-2017_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2017-2018_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
   - 2018-2019_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff.csv
NBA_Team_Stats_2010-2019_Rolling_Avg_Win_Loss_pts_diff_player_features:
   - 2009-2010_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2010-2011_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2011-2012_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2012-2013_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2013-2014_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2014-2015_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2015-2016_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2016-2017_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2017-2018_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
   - 2018-2019_NBA_Box_Score_Team-Stats_w_rolling_avg_win_loss_pt_diff_player_features.csv
NBA_Player_stats_raw:
  - NBA-2009-2010-Player-BoxScore-Dataset.xlsx
  - NBA-2010-2011-Player-BoxScore-Dataset.xlsx
  - NBA-2011-2012-Player-BoxScore-Dataset.xlsx
  - NBA-2012-2013-Player-BoxScore-Dataset.xlsx
  - NBA-2013-2014-Player-BoxScore-Dataset.xlsx
  - NBA-2014-2015-Player-BoxScore-Dataset.xlsx
  - NBA-2015-2016-Player-BoxScore-Dataset.xlsx
  - NBA-2016-2017-Player-BoxScore-Dataset.xlsx
  - NBA-2017-2018-Player-BoxScore-Dataset.xlsx
  - NBA-2018-2019-Player-BoxScore-Dataset.xlsx
NBA_Player_stats_w_rolling_avg:
  - NBA-2009-2010-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2010-2011-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2011-2012-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2012-2013-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2013-2014-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2014-2015-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2015-2016-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2016-2017-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2017-2018-Player-cleaned-Dataset_w_rolling_avg.csv
  - NBA-2018-2019-Player-cleaned-Dataset_w_rolling_avg.csv
