Num_Wins_L10G: {Description: 'Number of wins in the last 10 games, NaN if not applicable',
                Parameter_Name: Num_Wins_L10G,
                column_required: 'requires team_won column',
                method_of_compute: count,
                rolling_window_required: 10}

Num_Wins_L9G: {Description: 'Number of wins in the last 9 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L9G,
               column_required: 'requires team_won column',
               method_of_compute: count,
               rolling_window_required: 9}

Num_Wins_L8G: {Description: 'Number of wins in the last 8 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L8G,
               column_required: 'requires team_won column',
               method_of_compute: count,
               rolling_window_required: 8}

Num_Wins_L7G: {Description: 'Number of wins in the last 7 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L7G,
               column_required: 'requires team_won column',
               method_of_compute: count,
               rolling_window_required: 7}

Num_Wins_L6G: {Description: 'Number of wins in the last 6 games, NaN if not applicable',
               Parameter_Name: Num_Wins_L6G,
               column_required: 'requires team_won column',
               method_of_compute: count,
               rolling_window_required: 6}

Num_Wins_L5G: {Description: Number of wins in the last 5 games, NaN if not applicable,
               Parameter_Name: Num_Wins_L5G,
               column_required: requires team_won column,
               method_of_compute: count,
               rolling_window_required: 5}

Num_Wins_L4G: {Description: Number of wins in the last 4 games, NaN if not applicable,
               Parameter_Name: Num_Wins_L4G,
               column_required: requires team_won column,
               method_of_compute: count,
               rolling_window_required: 4}